# Generated by Django 4.2.2 on 2023-06-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stud_info",
            fields=[
                ("stud_id", models.AutoField(primary_key=True, serialize=False)),
                ("stud_fname", models.CharField(blank=True, max_length=55, null=True)),
                ("stud_lname", models.CharField(blank=True, max_length=55, null=True)),
                ("stud_class", models.CharField(blank=True, max_length=10, null=True)),
                ("stud_email", models.EmailField(max_length=254)),
                ("stud_age", models.IntegerField()),
                ("stud_address", models.TextField()),
                ("stud_city", models.CharField(max_length=99)),
                (
                    "stud_contact",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("stud_bloodgroup", models.TextField()),
                ("stud_DOB", models.DateField()),
                (
                    "stud_gen",
                    models.CharField(
                        choices=[("male", "MALE"), ("female", "FEMALE")], max_length=6
                    ),
                ),
            ],
        ),
    ]
